### ISSUE TITLE
Missing fields DeHaan

### ISSUE THREAD

**Issue by DutchPirate1966** [sejarah-nusantara/site#3]
See RFP for the numbers ...
1 - Missing [2] [6e] [6f] [6h] [7b]
2 - Missing in [1] text 'Map:' (language dependant text)
3 - Missing in [8] text: 'Bijlagen Resoluties:' (language dependant text)

**Comment by jellegerbrandy** [comment]
- [x] [2]
- [x] 6e (color)
- [x] 6f (typeGraphics)
- [x] 6h date
-[ ] 7b (refOriginalEN) --> marco heb je een voorbeeld waar het niet werkt?

2 en 3 gedaan..

**Comment by DutchPirate1966** [comment]
Voorbeeld van 7b is: B18 waar het veld <refOriginalEN> is gevuld met: Bijlage Resolutie 20 Maret 1752

**Comment by jellegerbrandy** [comment]
hiero, is goed zo? 
https://dasawebsite.cortsfoundation.org/search-maps/?ID=B18&description=&index_term=&text=&order_by=
