### ISSUE TITLE
DeHaan ... missing thumbnails

### ISSUE THREAD

**Issue by DutchPirate1966** [sejarah-nusantara/site#6]
In the column Identification the thumbnails to the scans are missing.
Thumbnails will need a hyperlink to page browser as well.

**Comment by jellegerbrandy** [comment]
Ik kan geen een werkend plaatje vinden in de repository.

De meeste plaatjes zie ik zoek (bv. alles met archiveFile A) bestaan niet in de repository (ik neem aan dat jullie die nog moeten toevoegen).
Maar wat vreemder is, is dat de plaatjes die er wel zijn, kapot  lijken. kijk bv hier: https://repository.cortsfoundation.org/scans?folioNumber=0006; geen enkele van de image_url links doet het. Weetj jij waar dat van komt?

**Comment by jellegerbrandy** [comment]
En wat betreft de links naar de pagebrowser: het lijkt er op dat de relevante boeken nog niet zijn gepubliceerd, Klopt dat?

**Comment by DutchPirate1966** [comment]
Niet alles is in test/staging aanwezig en gepubliceerd.
Maar bv deel D, E en F wel. Dus dat is testmateriaal.
Op prod is alles er al wel, maar ja dat is prod.
Het zou heel erg moeten lijken op wat we bij deel 1 van Corpus Diplomaticum hebben gedaan
En dat werkt
Een voorbeeld van een scan van DeHaan is http://repository.cortsfoundation.org/scans/565963
Ik zou verwachten dat zoiets als dit zou moeten werken voor subscollectie D: https://dasawebsite.cortsfoundation.org/pagebrowser/DeHaan-11-1/#source=D&page=2&accessor=thumbnails&view=
Maar misschien schiet ik dan mis met deze URL

**Comment by DutchPirate1966** [comment]
Ik zie nu wel een poging om de thumbnail te laten zien, maar een verbroken link blijkbaar want het plaatje is niet zichtbaar. Ook mis ik de 'achterkant' van de kaart, de thumbnail van de (eventuele) scan van die achterkant.

**Comment by DutchPirate1966** [comment]
[CollDeHaan_inventory_V20180725_2.xlsx](https://github.com/sejarah-nusantara/site/files/2228298/CollDeHaan_inventory_V20180725_2.xlsx)

**Comment by jellegerbrandy** [comment]
ok we hebben nu 2 thumbnails, voor en achter, met links
