### ISSUE TITLE
Error page bij browse maps

### ISSUE THREAD

**Issue by DutchPirate1966** [sejarah-nusantara/site#8]
Ik krijg deze error pagina op 
https://dasawebsite.cortsfoundation.org/browse-maps/?page=49 
Maar niet op de pagina ervoor of erna (vreemd)
Zie screenshot
![screen shot 07-25-18 at 09 42 am](https://user-images.githubusercontent.com/36985551/43186654-a015b1de-8fef-11e8-83eb-7592b0897e7b.PNG)

**Comment by jellegerbrandy** [comment]
ok, dit wordt verzoorzakt door regel 970 in het excel sheet waar de code `ID-ANRI_KG-1_M-0017A-A1` staat. Ik naam aan dat dat een typefout is en het `ID-ANRI_KG-1_M-0017A1` moet zijn

**Comment by DutchPirate1966** [comment]
Ik maak er het volgende van in de data: ID-ANRI_KG-1_M-0017A_A1 ... dus een onderliggend streepje ipv een verbindingsstreepje

**Comment by jellegerbrandy** [comment]
:+1: werkt
